### ISSUE TITLE
Cancel button not working

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-1#63]
**To Reproduce**
1. Draw something
![image](https://user-images.githubusercontent.com/9064351/79061425-c642fd00-7cc2-11ea-8930-2c03157ce6a7.png)
2.  Double click to edit and click ok
![image](https://user-images.githubusercontent.com/9064351/79061448-04d8b780-7cc3-11ea-9e94-c049e8c1f1c8.png)

3. click cancel button at bottom right corner
![image](https://user-images.githubusercontent.com/9064351/79061493-64cf5e00-7cc3-11ea-89b7-101d8b5e2155.png)
4. 
![image](https://user-images.githubusercontent.com/9064351/79061501-7c0e4b80-7cc3-11ea-88af-4122d8919f9a.png)

**Expected behavior**
It should not have render the structure

**Desktop (please complete the following information):**
Operating System: Microsoft Windows 10 Pro for Workstations 64bit [10.0.19041.0] en-GB
Word Product: Microsoft Office 365 Professional Plus 64bit [16.0.12624.20442]
Internet Explorer Version: 11.0.19041.153
.Net Framework Runtime: .NET 4.8 [528372]

**Comment by MikeWilliams-UK** [comment]
This is by design.

The user has already said they want the changes to be saved when they clicked ok on the editor dialogue.

The cancel on the edit labels dialogue (when popped up after an edit) is to only cancel any editing of the labels, NOT cancel the saving of the changes performed in the editor.

The label editor is popped up after saving an edited structure to allow the user to optionally remove any labels which have been invalidated by the editing operation.

**Comment by MikeWilliams-UK** [comment]
Chem4Word has operated in this manner since version 2.0.1.0 which has been in use since at least August 2016 (I can only trace back this far as this is when we moved the code from CodePlex to GitHub)
